c1:												#$ make c1	# компиляция программы 1
	gcc one.c -lrt -pthread -o one.out
r1:												#$ make r1	# запуск программы 1
	./one.out
c2:												#$ make c2	# компиляция программы 2
	gcc two.c -lrt -pthread -o two.out
r2:												#$ make r2	# запуск программы 2
	./two.out