all:
	mkdir -p bin
	cd bin; gcc ./../src/main.c -o app

clean:
	rm -rfv bin

run:
	cd bin; ./app

test1:
	cd bin; ./app 1 12 123 1234 12345 123456 1234567 12345678 123456789 1234567890

test2:
	cd bin; ./app banana cherry lemon orange watermelon